// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Components/Component/index.js

(module.exports = require('./namespace'))

.addModules({
  Basics:              require('./Basics'),
  CanUpdateFrom:       require('./CanUpdateFrom'),
  ChildrenProp:        require('./ChildrenProp'),
  Clone:               require('./Clone'),
  CoComponnentUpdates: require('./CoComponnentUpdates'),
  Inspection:          require('./Inspection'),
  LifeCycle:           require('./LifeCycle'),
  Refs:                require('./Refs'),
  RootElementUpdates:  require('./RootElementUpdates'),
  State:               require('./State'),
  StateFields:         require('./StateFields'),
  UpdateFrom:          require('./UpdateFrom'),
  WrapperComponents:   require('./WrapperComponents')
});