# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Components/Component/namespace.coffee

module.exports = (require '../namespace').addNamespace('Component', class Component extends Neptune.PackageNamespace)
