// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Components/Component/namespace.js

module.exports = require('../namespace').addNamespace(
  'Component',
  class Component extends Neptune.PackageNamespace {}
);
