// generated by Neptune Namespaces v4.x.x
// file: tests/Mocks/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Mocks'))
.addModules({
  TestSpecializationElement:                  require('./TestSpecializationElement'),
  TestSpecializationRecyclableVirtualElement: require('./TestSpecializationRecyclableVirtualElement'),
  TestSpecializationVirtualElement:           require('./TestSpecializationVirtualElement')
});