# generated by Neptune Namespaces v3.x.x
# file: tests/Mocks/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Mocks'
.addModules
  TestSpecializationElement:                  require './TestSpecializationElement'                 
  TestSpecializationRecyclableVirtualElement: require './TestSpecializationRecyclableVirtualElement'
  TestSpecializationVirtualElement:           require './TestSpecializationVirtualElement'          