// generated by Neptune Namespaces v4.x.x
// file: perfs/Art.Components/index.js

(module.exports = require('./namespace'))

.addModules({
  ObjectTreeFactory:  require('./ObjectTreeFactory'),
  RecycleExperiments: require('./RecycleExperiments'),
  Render:             require('./render')
});