# generated by Neptune Namespaces v3.x.x
# file: perfs/Art.Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ObjectTreeFactory:  require './ObjectTreeFactory' 
  RecycleExperiments: require './RecycleExperiments'
  Render:             require './render'            