// generated by Neptune Namespaces v4.x.x
// file: perfs/Art.Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Components',
  (class Components extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
