# generated by Neptune Namespaces v3.x.x
# file: perfs/Art.Components/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Components', class Components extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
