# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Counters:               require './Counters'              
  PerfRegressions:        require './PerfRegressions'       
  StandardImport:         require './StandardImport'        
  Test:                   require './Test'                  
  VirtualElementExtended: require './VirtualElementExtended'
require './Component'