# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Counters:                 require './Counters'                
  EpochedStateMixin:        require './EpochedStateMixin'       
  PerfRegressions:          require './PerfRegressions'         
  RecyclableVirtualElement: require './RecyclableVirtualElement'
  StandardImport:           require './StandardImport'          
  Test:                     require './Test'                    
  VirtualElement:           require './VirtualElement'          
require './Component'