// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Counters:                 require('./Counters'),
  EpochedStateMixin:        require('./EpochedStateMixin'),
  PerfRegressions:          require('./PerfRegressions'),
  RecyclableVirtualElement: require('./RecyclableVirtualElement'),
  StandardImport:           require('./StandardImport'),
  Test:                     require('./Test'),
  VirtualElement:           require('./VirtualElement')
});
require('./Component');