// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Components',
  class Components extends Neptune.PackageNamespace {}
);
require('./Component/namespace');