# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Components/namespace.coffee

module.exports = (require '../namespace').addNamespace('Art.Components', class Components extends Neptune.PackageNamespace)
require './Component/namespace'