// generated by Neptune Namespaces v4.x.x
// file: Art.Components/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Components'))
.addModules({
  Component:                    require('./Component'),
  ComponentEpoch:               require('./ComponentEpoch'),
  Counters:                     require('./Counters'),
  DevMode:                      require('./DevMode'),
  EpochedStateMixin:            require('./EpochedStateMixin'),
  Helpers:                      require('./Helpers'),
  Init:                         require('./Init'),
  InstanceFunctionBindingMixin: require('./InstanceFunctionBindingMixin'),
  RecyclableVirtualElement:     require('./RecyclableVirtualElement'),
  RootComponents:               require('./RootComponents'),
  StandardImport:               require('./StandardImport'),
  StateFieldsMixin:             require('./StateFieldsMixin'),
  VirtualElement:               require('./VirtualElement'),
  VirtualElementPool:           require('./VirtualElementPool'),
  VirtualNode:                  require('./VirtualNode')
});