// generated by Neptune Namespaces v4.x.x
// file: Art.Components/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Components',
  (class Components extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
